# Generated by Django 5.1.1 on 2024-11-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='motive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(default='unknown@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
