# Generated by Django 5.1.1 on 2024-11-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
