# Generated by Django 5.1.1 on 2024-12-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_alter_appointment_requested_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
    ]
